msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2017-04-20 02:58+0300\n"
"PO-Revision-Date: 2017-04-20 02:59+0300\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: tr_TR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 2.0.1\n"
"X-Poedit-Basepath: Downloads/calibre-cloud-plugin-master\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Poedit-SearchPath-0: main.py\n"

#: main.py:75
msgid "Login information is incorrect!"
msgstr "Giriş bilgileri yanlış!"

#: main.py:81
msgid ""
"It was created because there is no Calibre file in Drive, download could not "
"be done."
msgstr ""
"Drive'da Calibre dosyanız olmadığından oluşturuldu, download yapılmadı."

#: main.py:84 main.py:241
msgid "Download complete."
msgstr "İndirme tamamlandı."

#: main.py:89 main.py:234
msgid "Upload complete."
msgstr "Yükleme tamamlandı."

#: main.py:93
msgid ""
"It was created because there is no Caliber file in Drive, pull could not be "
"done."
msgstr "Drive'da Calibre dosyanız olmadığından oluşturuldu, pull yapılmadı."

#: main.py:96
msgid "Pull complete."
msgstr "Pull tamamlandı."

#: main.py:101
msgid "Push complete."
msgstr "Push tamamlandı."

#: main.py:243
msgid "Calibre file does not exist on your Drive!"
msgstr "Drive'ınızda Calibre dosyası mevcut değil!"
